---
# Sample commands from the parent directory:
# ansible-playbook common/git_repo.yml -e the_project="{{ project_my_webservers_dev }}"
# ansible-playbook common/git_repo.yml -e the_project="{{ project_my_webservers }}"
- name: Change setting in GitLab to allow webhooks from controller VM
  hosts: workstation
  gather_facts: no
  vars:
    gitlab_api_token: redhat-training-gitlab-api-token
  tasks:
    #- name: Fail if action is not defined
    #  assert:
    #    that: the_project is defined
    #    success_msg: The 'action' variable is defined.
    #    fail_msg: The 'action' variable must be defined.

    - name: Change GitLab settings from API
      uri:
        url: https://git.lab.example.com/api/v4/application/settings?signup_enabled=false&{{ attributes | join('&') }}
        method: PUT
        headers:
          private-token: "{{ gitlab_api_token }}"
        status_code:
          - 200
          - 201
      vars:
        attributes:
          - allow_local_requests_from_web_hooks_and_services=true
          - allow_local_requests_from_system_hooks=true
          - outbound_local_requests_allowlist_raw=lab.example.com
