---
- name: Playbook to test Ansible Navigator
  hosts: all
#  serial: 1
  tasks:
    - name: Testing Connectivity with Ping Module
      ansible.builtin.ping:

    - name: Displaying Host Output
      ansible.builtin.debug:
        msg: Hello, I'm {{ ansible_facts['hostname']  }} and my kernel version is {{ ansible_facts['kernel'] }}.
